Refactor jobs, add default option support and cleaned unnecessary code (#18)
* remove branch name in script comment

* removed EnvVarsRust due to not being a good thing to centralise

* removed unnecessary funcs and renamed conclusionAll to conclusion

* add support for default option

* added release type validation job

* removed MatricesRust due to not being good enough to centralise

* added whitelist PR Heads to Branch job

* fix new line formatting

* reduce 1 space in print allowed branches statement

diff --git a/.github/workflows/policy-branch-protection.yml b/.github/workflows/policy-branch-protection.yml
--- a/.github/workflows/policy-branch-protection.yml
+++ b/.github/workflows/policy-branch-protection.yml
@@ -25,4 +25,36 @@ jobs:
         fetch-depth: 1
     - name: Ensure PRs to main branch are only from allowed branches
       shell: bash
-      run: tools/scripts/ci/protect-main-branch.sh
+      run: |-
+        # Define target branch
+        TARGET_BRANCH="main"
+
+        # Define allowed branch prefixes as an array
+        ALLOWED_PREFIXES=("feature/"
+        "bugfix/"
+        "refactor/"
+        "chore/"
+        "bump/"
+        "dependabot/")
+
+        # Convert array to regex pattern
+        ALLOWED_PATTERN="^($(IFS='|'; echo "${ALLOWED_PREFIXES[*]}"))"
+
+        # Check if the pull request is targeting the branch
+        if [[ "$GITHUB_BASE_REF" == "$TARGET_BRANCH" ]]; then
+          # Check if the source branch follows the allowed naming pattern
+          if ! [[ "$GITHUB_HEAD_REF" =~ $ALLOWED_PATTERN ]]; then
+            printf "Error: Pull requests to '%s' can only be from these branches:\n" "$GITHUB_BASE_REF"
+            for branch in "${ALLOWED_PREFIXES[@]}"; do
+              printf " - %s\n" "$branch"
+            done
+            exit 1
+          else
+            echo "Pull request to '$TARGET_BRANCH' from allowed branch '$GITHUB_HEAD_REF'."
+          fi
+        else
+          # If not targeting the target branch, skip the check
+          echo "Pull request is not targeting '$TARGET_BRANCH'; skipping the check."
+        fi
+
+        exit 0
